default: &default
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: postgres
  password: admin
  template: template0

development:
  <<: *default
  database: newsfeed_development


test:
  <<: *default
  database: newsfeed_test


production:
  <<: *default
  database: newsfeed_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
